### ISSUE TITLE
cannot use openapi3.Components{…} (value of type "github.com/getkin/kin-openapi/openapi3".Components) as *"github.com/getkin/kin-openapi/openapi3".Components value in struct literal

### ISSUE THREAD

**Issue by badsgahhl** [go-goyave/openapi3#2]
Hello,

i wanted to install the SwaggerUI feature from this documentation link: https://goyave.dev/guide/libraries/openapi.html#swaggerui

After installing goyave.dev/openapi3 and setting up the code in my router the following error occures:

```
# goyave.dev/openapi3
..\..\..\..\go\pkg\mod\goyave.dev\openapi3@v0.2.1\openapi.go:46:15: cannot use openapi3.Components{…} (value of type "github.com/getkin/kin-openapi/openapi3".Components) as *"github.com/getkin/kin-openapi/openapi3".Components value in struct literal
```
![image](https://github.com/go-goyave/openapi3/assets/28596891/4e9f6a6b-c724-4563-9a64-3ca0d2f40c3a)

**Comment by System-Glitch** [comment]
It looks like a breaking change that occurred in kin-openapi v0.113.0 ([ref](https://github.com/getkin/kin-openapi/compare/v0.112.0...v0.113.0#diff-2fee11be44932b92b1e1bae0c976eb01bf4b05f97acc225464254d70c8535497R16)). 

Quick fix for you: downgrade `github.com/getkin/kin-openapi/openapi3` to `v0.112.0`

I'm sorry I don't have the time to maintain this library myself for now, as I'm fully focused on v5 for the core of the framework. I'm very much open to contributions though!

**Comment by badsgahhl** [comment]
PR in #3 . Should fix the problem. Tests ran successfully and it works at least in my project now.
